trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:

# Checkout the code from the specified repository
- task: Checkout@1
  displayName: 'Checkout Code'
  inputs:
    repository: 'https://github.com/Nishalaxmi/Employee.git'

# Pre-build step: Install dependencies
- task: UseNode@2
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '16.x'
    checkLatest: true

- script: npm install
  displayName: 'Install Dependencies'

# Build step
- script: npm run build
  displayName: 'Build Project'

# Post-build step: Archive artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish Build Artifacts'
  inputs:
    PathtoPublish: 'dist/'
    ArtifactName: 'drop'

# Post-build step: Send mail notification
- task: Mail@1
  displayName: 'Send Email Notification'
  inputs:
    To: 'nishagold356@mail.com'
    Subject: 'Azure DevOps Pipeline Build Notification'
    Body: |
      The build pipeline has completed successfully. 
      Artifact is published and ready for deployment.
    Attachments: '$(Pipeline.Workspace)/**/*.zip'
